language: python
python: '3.6'
services:
- docker
install:
- pip install -r requirements.txt
deploy:
  provider: script
  script: make build push
  on:
    branch: add-travis
env:
  matrix:
  - secure: u3Eny16OpWYs6r0R3B1jqwtzSynZ+mHNrzIhg3lipqbUZlDpV5y412jWhg3kYv48dIUWkB6RcPdivfysQBsJoPeMuNTfKIB9RwNeER2U9a1Yxtb2sJjU2PI11IjZS3OZvLlHKu0qCBNqwX2l9D1s5s6rNUb+shHgf6+64BFySto0pylMpBWAW+VjVQUJdhSghZSW8fOueyTeGjvZrjQf4+k/+YTLEHKjZabcLcjz9QEZ8SCUxeJANcpqWf+i5lWxP9BJ5iRE4hMu5COvZl/YyDYw39jEbFA5hL25fIlbkP1YJPqUYBeccl7zGCvn96FxKAqIO/HvaMeZM1HFedEjirDo7Y/JcWQJ3S3OE8/w1n5eXx+wP28F7hQEvWaeF1zz/AHUSjeYIhbJoZ7rx/iih95xPbyQiahCGlALcKnZV82IPrsMZeAo2lJtF+TtHCTbVxgpitvfXNU8fuf/DF5++7Oy8OtdjyqDV8lqLUPb7MtIPi4khMtIbCtrYwIUhtB7+ZH0SAueSZ3LMa77Qkdff9DwgIXE/Yw/+o4QCC42sKoiRYxM8X6NutqcAsi1TgQZZtblxYUMVNALSY/KYyb8apxVrZzXyg9PDyL1rw6RgDqOzAiSwqy1JOd0rqJWldiGKMhqoXjbdHBSrF+uxffUwBQ9AmJtlptqYxvJPMgA9BU=
  - secure: I9XzYUgCrskQzabNo8OodMaDG5nqhYIjBW0GcHvIM7dpID8iSBZkpN2f8YYvNLCYhR/yuintaeZHXHBQSzbQSjbf4nrxhj0K6/ZLP1q+qq4zBbAsafSTXl2zaRlQbweoS1EM20uzWEzCkvC/jikHwVPS42uUGjko4xdKDQohAH/ENFsWGC64rM+FsivzjzyzvlZUWJy5MiNaLFrNM6w9c2gSZDPuWapBxQPdTeLkLg1EMTuJGk6xB2aGQ+zzdjr6ctoJoCwvouqV+Bn9EzLgjbUpKpOy3KY9x6F6dcTBPDmgwWhWSg7feKxRFPDnHnDQJkUsMU6FDaYGRm+Js7YnA9CSSaB9Tcj8ir06XMyj8Jkolp6PeO6UYHrm4mazXJDSoRgZirPh+QC3XKQbzoc5PruTqZq1IJGDbjIMemwPJ/WvgFeLyJllgxjicLXoCDjmQ466ZSc+t5TXL/KU7jvzxB5MxLkqif4t+4vHcjnyFTRYwp/fA1qDaH35yZM6//l8gVmcjXILPEBtVdUk/huK3ADarE+95g6GE4tOu973gjWhxr1S7KRz9hVuS2H9PBzx96RJWauhMNW0bmgYyPXil66fbM8VKhsg+kDTp5+3SnIT8mgFKopwwVzp25AlsMkinfdAxpZ/fv36+v12haUc18CI+98fGNa+u9ZWk3C4PfM=
