language: python
python: '3.6'
services:
- docker
install:
- pip install -r requirements.txt
deploy:
  provider: script
  script: make build push
  on:
    branch: add-travis
env:
  matrix:
  - secure: Le2COGintfp0XGPujnMSjI/Diz4tdWMVib7b2BptifXFVzX+PcHmP3V8wthMR2OhMaB4YIQeiDJeUkuHEIpdbRpSqc5A8pfUSSuh0CDXS+9kXo025edS1Iyz1J9G/gPLfI8WMbRXsK3QNz+Tz+MrFh3rCekkPkxx3nhSpaThPfSZJ9kTqzQb9S2cDxeYouikOPtOvS6bs31lsgOGzjPXwRI65ocIxR8jiwwPN0ycgb5LGeKWiG5AhNqnpU0WcvQqaKF3CTLs5e/p1E7RRVsXsGn4lSGdpL4FNj/TogoRW+2vXbU0bx4Uxp8+2ceIs/0h22P73DiV/lR5tzrhXEWfK4kks6d00J2s/1wUcBesFIG5kIeuxDMV8L0RntRqQCH9Uc6f3VjNfNR9albjtIcz3IKKgxDU2WT6snjTfoKRZMR1HN3gxSB/hORJQBqSVX29RrRGWjcPUgN0VW+tjAbYssjjcEXIA46kvk6U0AOPUrxfIgR/GeArEMPjRfMdgRDADuqSIfN38SRINL+iLQ1+Brp8eKZ3S7loku2HSYCv2cv+jYCDBbQ5RH5iCvDsju3W7kw5CctkoboBU7GnBLxEmgqc5BTbaHpEwvM46TcmH0T/bZlgLj8tI89hEOYaglVFQf4LazG5voIiUsLb2L0wAUO+Q3+fckVfpWtulSXe7f8=
