language: python
python: '3.6'
sudo: required
services:
  - docker
script:
  - make test build
deploy:
  provider: script
  script: make push
  on:
    branch: master
env:
  global:
  - DOCKER_USERNAME=swallowstalker
  matrix:
  - secure: qKku0L6Dtf05QJuvS5l65PzaCIKwy5Xz0y75rboSsW7sFtwgCfDBH4oKGXDS41+UagYYdViS5FPe1CNy+dsK0XhebOBSOOp4HDJh1GkZ961Gq+3XvvBMeOUQ/GrhpuyJ6xpMfUBWuM1x+yCvCBbOM6HtRILbX5+ddzYMJkaIc1SCHqLROAps85hLqpToWgmHIzzjjfSQIK/BW4CSqzbmRW2WFzEdO1n6T3bHURKM4ridaUpMZkOfYwaAezjK7dizCqfBY8PDMjbeHTCNVDvjdx/AdL8j+x+HYHvdA1oAl2tY1Mr2DmVz32s8k092FEJBRGPAJ6Gzn4ogC7qnPLTzRscE0ZTDgo7sJCVSFyaujIf727ucmpwCnBw9LYlXa35uRhxOoj5oHauILoCvyCVcos5yI+fPZRLzkHL5kFkfqDxy8z/mNrNhmH/4W/B7VvGkxV5Mwo54ZuRaRXmZyVWweusW9leXJVU/MP0nSWryRkMZmhZTPMqC9tgSl9CJv1fOQzUoXTBWetz2v82My9Y0thzn5O1KxBxEw/mJT552QUTLWiKTQOFEDYNVM/jU9VQMOZ+30vKC4n2idmQWgFA+ND+kjpgK33qqOkMklTVeaUGSDYUgCT6EMlmevbvmhn6Veks4K+uc4YWYOlaYFO7sVZ2bkWT1PB3sEmlaNA+8vVc=
